### ISSUE TITLE
Load Mode demo has missing "gef-pagination-label" element

### ISSUE THREAD

**Issue by nickshanks** [bbc/gef-docs#112]
The `<nav>` around the pagination component of the Load More demo has an `aria-labelledby="gef-pagination-label"` attribute, but there is no element with `id="gef-pagination-label"` on the page. The nav element just gets described as an anonymous navigation landmark in the VoiceOver rotor.

**Comment by Heydon** [comment]
@nickshanks Good catch! I'll get that fixed ASAP.

**Comment by Heydon** [comment]
Done in https://github.com/bbc/gef-docs/pull/117
