### ISSUE TITLE
Add label to Promo

### ISSUE THREAD

**Issue by micmath** [bbc/gef-docs#116]
Where the "label" is what GEL calls the little text overlay on the corner of the Promo image.

**Comment by simonsinclair** [comment]
I am happy to be assigned to this. For reference, are we talking about `NEW` in the upper-left hand corner of this Promo?
![Screen Shot 2019-06-20 at 10 55 26](https://user-images.githubusercontent.com/1430787/59840377-20488f80-934a-11e9-88e8-b16579c6a587.png)

**From GEL**

> A label is a temporary indicator used to attract attention to a piece of content. It’s letting you know why you are seeing this. Typical uses are:
> **State**: To show where a piece of content is within the contents lifecycle, e.g. if a piece of content is currently in progress or due to expire. This is in place of or with a progress bar.
> **Editorial**: To show that there’s something special about that content i.e. ‘new’ or ‘exclusive’.

**Comment by micmath** [comment]
@simonsinclair you may want to ask @Heydon about any advice for the screen reader experience of a promo label. I can't guess what they should "sound" like.

**Comment by Heydon** [comment]
@simonsinclair @micmath I anticipate the solution (for the purposes of structure/reading order) will be along the lines of

1. Hiding the visible label with `aria-hidden="true"`
2. Prepending "New:" to the main title/heading/link text for the link, in a visually hidden span (`<span class="gef-sr">New:</span>)

**Comment by simonsinclair** [comment]
Thanks, @Heydon!

**Comment by simonsinclair** [comment]
See pull request https://github.com/bbc/gef-docs/pull/118.
