### ISSUE TITLE
Menu Drawer Pattern

### ISSUE THREAD

**Issue by micmath** [bbc/gef-docs#59]
There has been a request from a product team for advice regarding a navigational pattern that is used in many places around the BBC. For lack of a better name I'm calling it a Menu Drawer but I'm happy to be corrected if that is not the best title.

It's frequently used in secondary navigation. I can't find it specifically documented in GEL but it is related to [Tabs](https://www.bbc.co.uk/gel/guidelines/tabs) and [Filter](https://www.bbc.co.uk/gel/guidelines/filter). The overflow behaviour in particular is already addressed in our [Masthead](https://github.com/bbc/gef-docs/blob/master/src/components/masthead.md) documentation, but can we have a component document that is very specifically focused just on the simple tab/drawer pattern used in navigation.

I've attached some screengrabs showing examples of the pattern.

![screenshot 2019-01-25 10 24 25](https://user-images.githubusercontent.com/81645/51741045-af989200-208d-11e9-9323-d69cbedc7bca.png)
![screenshot 2019-01-25 10 25 14](https://user-images.githubusercontent.com/81645/51741047-af989200-208d-11e9-9cb2-59631f670979.png)
![screenshot 2019-01-25 10 28 33](https://user-images.githubusercontent.com/81645/51741048-af989200-208d-11e9-83f2-251ee95f1c4e.png)

**Comment by Heydon** [comment]
@micmath Sorry, I guess I wasn't clear: I'm not conflating the two (Masthead and Menu drawer), I just mean they have a similar problem to be solved. That is, the top-level options all come before the submenus (at least if we want the submenus to be statically positioned). So, when you click the first top-level option, you would have to tab through all the other top-level options to get to the submenu. In the Masthead and custom Tabs interfaces, this is fixed by using focus management. It's fine, but a bit hacky. An Accordion (top-level/submenu/top-level 2/submenu 2 etc) doesn't have this problem.

**Comment by micmath** [comment]
Oh 😲 I see! Yep. masthead is a bit of a red herring in this case, and I'm the one who brought it up so I have no one to blame but myself!

I think in a JS-enabled client we would throw focus down to the drawer panel when it opens, and back to the tab label when it closes. Not sure what to do in an non-JS client, but I think that might be the issue you are thinking about? That seems quite tricky to be honest. Is it one that you want to take on?

**Comment by Heydon** [comment]
@micmath Interesting! It does some weird CSS stuff with floats to bring the submenu underneath. I can try to emulate that.

**Comment by micmath** [comment]
I'll remove the "Promo Group" doc in the project plan and replace it with this topic, if you agree @Heydon

**Comment by Heydon** [comment]
@micmath Sure, I think we have time to fit this one in.

I will update Promos on Monday anyway, with the headings stipulations, use of `<aside>`, and a bit under layout about 'promo groups'.

**Comment by micmath** [comment]
Thanks very much! :star:

**Comment by Heydon** [comment]
@micmath In terms of structure (nested lists) and intent, this is a table of contents, so I'm using `gef-toc`. What do you think? I took what you did and am building it out.

**Comment by micmath** [comment]
Makes sense semantically, it is "_local_ navigation".

**Comment by Heydon** [comment]
> Makes sense semantically, it is "local navigation".

@micmath Right! I think it needs to be a `<nav>` landmark, with a label like "Site". Could then update the label for the Masthead `<nav>` to be "BBC sites" or similar?

**Comment by micmath** [comment]
Yes, that!
