### ISSUE TITLE
Tabs - Last merge bug with 'Related research'

### ISSUE THREAD

**Issue by greenc05** [bbc/gef-docs#87]
Think our last code merge went a touch wrong, we have '<<<<<<< HEAD' and some other rubbish in the 'Related research' section

https://bbc.github.io/gef-docs/components/tabs/#related-research

**Comment by micmath** [comment]
Well spotted: fixed.

**Comment by greenc05** [comment]
Thanks, I guess it takes a while to get to live...

**Comment by greenc05** [comment]
Thank you
