### ISSUE TITLE
Tabs list - NVDA improvement

### ISSUE THREAD

**Issue by greenc05** [bbc/gef-docs#88]
When using NVDA the usual behaviour is for it to read out a list with one press of the down arrow key, this can be applied to our tab list.

Currently in the reference implementation you have to press the down arrow key 3 times to move through the tab list. While I realise this isn't a real world example and meant to be used as reference, for developers referring to the reference implementation, it would be nice if this reflected expected screen reader UX.

This can be fixed (and improve the screen reader UX particularly if there are a good few tabs to move through,) with the following CSS (note not thoroughly browser tested):

- Change display block to display inline-block for .gef-tabs > ul a 
- Add text align center and background color #dcdcdc to .gef-tabs > ul [role="presentation"]
- And therefore text-align center is no longer needed on .gef-tabs > ul [role="tab"]
- And background color #dcdcdc is no longer needed on .gef-tabs > ul a 
- And I believe we will need to apply a class with JS to the selected li so we can change the colour of the selected tab to #ccc. This means we can then remove the background colour for .gef-tabs [aria-selected]

Note, this should be fixed in the reference implementation and also reflected in the documentation write up

**Comment by micmath** [comment]
Pull request welcome :-)

**Comment by micmath** [comment]
Inviting @simonsinclair to look. @greenc05 are you happy to help him build up a pull request for this?

**Comment by greenc05** [comment]
Sure, I can change the CSS but I don't have the JS skills, maybe @simonsinclair does? Along with time to browser test? @simonsinclair?

**Comment by simonsinclair** [comment]
Hi @micmath and @greenc05, I'm happy to pick this up tomorrow morning. Regarding browser testing - what's the procedure?

**Comment by greenc05** [comment]
Fabulous thanks @simonsinclair - Just test on all the popular browsers IE11, FF, Chrome, Safari etc @micmath might have a list for the project that they are using

**Comment by micmath** [comment]
We really should publish a list of browsers we test on. I'd love to have that be based on what Web Core are testing on actually. Does anyone know what their list is?

**Comment by greenc05** [comment]
News browsers are based on user stats, this will differ per product, so yes probably best to get a steer from Web Core.

**Comment by simonsinclair** [comment]
Hi @greenc05 and @micmath, I'm trying to understand this issue. On Friday I tried out the suggested CSS, but it changed the look of the component. Also:

- Tabs already have JS logic controlling their active highlight. Am I right in thinking the request was for the highlight logic to be changed to highlight the parent `<li>` rather than the `<a>`, because of the amended CSS?
- Also, so I can understand, how is the amended CSS going to affect the behaviour of a screen reader? Will it skip past the tabs?

**Comment by greenc05** [comment]
@simonsinclair are you based in NBH? Might be best if we pair on this for half an hour and I can explain better? If not over a Slack call?

**Comment by simonsinclair** [comment]
Hey @greenc05, I'm in W12, but happy to do a Slack call. Today (11th) is fully-booked, but am available tomorrow or Monday?

**Comment by simonsinclair** [comment]
Hey @greenc05, it was good to catch up today. I took a look at this and have used `display: flex`, because inline-block was causing a visual regression and fixing it was getting hacky. However we need to make sure this works with NVDA. Please can you test the branch https://github.com/bbc/gef-docs/tree/tabs-list-nvda-improvement and let me know how it goes?

**Comment by greenc05** [comment]
@simonsinclair please could you create a PR for the branch? I will then try to make the changes locally on the PC to check it. Thanks again.

**Comment by micmath** [comment]
Related issue is flashing in my mind at this point, @greenc05 said "it would be nice if this reflected expected screen reader UX."

Does the BBC (via GEL ideally) actually define "expected screen reader UX" on this issue? I will genuinely be delighted to see that it does, but I know that in many cases the expected screen reader behaviour is conspicuously missing from the UX docs.

Not sure how to address that generally, could possibly be a big job to undertake.

**Comment by micmath** [comment]
Awaiting review comments by peeps who have expressed an interest, such as @JamieKnightBBC

**Comment by greenc05** [comment]
@micmath this was just a bug coming from our CSS - Not sure if you guys are testing the GEF output? This is default behaviour for NVDA users and that's all I meant by "it would be nice if this reflected expected screen reader UX... (in the reference implementation)."
