### ISSUE TITLE
Tabs - Missing the ability to active the tab by spacebar as well as enter

### ISSUE THREAD

**Issue by greenc05** [bbc/gef-docs#90]
Under 'Recommended behaviour - With JavaScript' https://bbc.github.io/gef-docs/components/tabs/#with-javascript 

In the 1st paragraph it says 'For keyboard users, unselected tabs are focusable and can be activated with the Enter key'.

I believe we have miss the spacebar from this? As per the W3C 'Space or Enter: Activates the tab if it was not activated automatically on focus.'

This should be updated on the documentation write up and also in the reference implementation.

**Comment by micmath** [comment]
fixed in https://github.com/bbc/gef-docs/pull/94
