### ISSUE TITLE
Improve local development experience by using hot and live reloading

### ISSUE THREAD

**Issue by simonsinclair** [bbc/gef-docs#95]
Having resolved a few tickets in bbc/gef-docs, I think we could benefit from triggering build automatically, plus hot and live reloading.

- This would speed up development and could be done using the popular BrowserSync module and a task-runner like Gulp without being invasive.
- Developers would be able to choose between running something like `npm run develop` or sticking to what they do now.

**Comment by micmath** [comment]
This has been merged. Nice work, @simonsinclair .
